### ISSUE TITLE
Create a counter project

### ISSUE THREAD

**Issue by AayushBiswas** [AayushBiswas/hacktoberfest_2022#1]
Create a project which has + and - button with a counter displaying the number

**Comment by TailisUI** [comment]
Hi I can work on this issue can you pls assign it to me

**Comment by TailisUI** [comment]
because I have already created it

**Comment by TailisUI** [comment]
because I have already created it

**Comment by AayushBiswas** [comment]
@TailisUI you can start working on this issue

**Comment by AayushBiswas** [comment]
Then you can send it in the prs
