### ISSUE TITLE
Create a navbar with sign up and sign in button

### ISSUE THREAD

**Issue by AayushBiswas** [AayushBiswas/hacktoberfest_2022#17]

**Comment by Deepanshu1008** [comment]
Can you assign me this task?

**Comment by Eazyisreal** [comment]
Kindly assign this task to me @AayushBiswas

**Comment by Mannu292001** [comment]
plz assign to me

**Comment by AayushBiswas** [comment]
one who will submit first will be accepted

**Comment by Eazyisreal** [comment]
@AayushBiswas  I have created a PR Chore:Fixed Navbar with sign in and sign up button #22
