### ISSUE TITLE
A react Based Note Making Webapp

### ISSUE THREAD

**Issue by iamwicked** [AayushBiswas/hacktoberfest_2022#44]
I made a React based Web Application with the add and delete functionality

**Comment by vishisht-dubey** [comment]
hii @iamwicked i am interested in solving this issue
would you please elaborate..

**Comment by vishisht-dubey** [comment]
@iamwicked also assign me with this one

**Comment by iamwicked** [comment]
Hey @vishisht08 I haven't added edit feature. You can work upon that.

**Comment by iamwicked** [comment]
Thanks @AayushBiswas for merging early.

**Comment by vishisht-dubey** [comment]
@iamwicked so where can i get the code of this in which i can make changes or i have to write everything on my own from scratch.

**Comment by iamwicked** [comment]
you can for the repo

**Comment by vishisht-dubey** [comment]
okk

**Comment by vishisht-dubey** [comment]
@iamwicked can you please explain more about edit feature as i see your code contains edit feature and it is also working so what i had to resolve.

**Comment by iamwicked** [comment]
A feature to edit the notes after it is created

**Comment by vishisht-dubey** [comment]
ohkk..
