### ISSUE TITLE
Cannot add my PHP project with MySQL  

### ISSUE THREAD

**Issue by mirazxmondal** [AayushBiswas/hacktoberfest_2022#47]
Hey, @AayushBiswas, I wanted to add a login authentication project which I made using HTML, CSS, JS and PHP, MySQL for backend I could not able to raise a PR for it as the repo did not recognised the files, I guess it was due to PHP files were there. Could it be a case? Because also I tried to add a plain HTML,CSS,JS project it immediately recognised.

**Comment by AayushBiswas** [comment]
To host PHP website you need to have an database online and to have that you need to buy hosting. The free solution is that go to Database and export the database as .sql file. And upload the .sql file in the repo.

Here is an link of how to do that:
https://www.hostinger.com/tutorials/export-mysql-database-with-phpmyadmin

**Comment by mirazxmondal** [comment]
Yes, I did exported the .sql file from phpmyadmin. This was the repo https://github.com/miraz-mondal/Login-Authentication I wanted to raise a PR.  [login.sql](https://github.com/miraz-mondal/Login-Authentication/blob/main/Assets/Database/login.sql) the .sql file but it I could not raise the PR as this repo was unable to recognise my project. Can you tell me what could be the issue?

**Comment by AayushBiswas** [comment]
Delete the hacktoberfest_2022 fork from your account and fork this repository. Now in that upload the files in specific folder and repository will recognize it
