### ISSUE TITLE
Create responsive website about F1

### ISSUE THREAD

**Issue by Suga7772** [AayushBiswas/hacktoberfest_2022#57]

**Comment by ishita126jain** [comment]
Hey @Suga7772 can I add my responsive website project.

**Comment by ishita126jain** [comment]
I have added my project of complete responsive Blogging website using html
, css and js can you please checkout my PR
thankyou for this opportunity.

**Comment by Suga7772** [comment]
Absolutely go for it !
All the best kudos aayush :D

**Comment by ishita126jain** [comment]
Thanks

**Comment by ishita126jain** [comment]
I think you go through my PR so if you find useful please let me know.
